services:

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-lmsevo-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        while ! nc -z db 5432; do
          sleep 1
        done &&
        echo 'Database is ready!' &&
        python -m db.setup_db
      "
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-lmsevo-db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database:/app/db  # Mount database directory to /app/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:password@db:5432/lmsevo-db}
      - SECRET_KEY=${SECRET_KEY:-your-very-long-secret-key-here-at-least-32-characters}
    depends_on:
      - db
      - db-init

volumes:
  postgres-data: 